Update download

diff --git a/download b/download
--- a/download
+++ b/download
@@ -13,24 +13,21 @@ set -o pipefail
 set -o nounset
 #set -o xtrace
 
-# Script running with pipeline executing
-if [ -z "${BASH_SOURCE[0]:-}" ]; then
-  __dir=/usr/local/bin
-  if [ ! -d ${__dir} ]; then
-    __dir=/usr/bin
-  fi
-
-  version=${1:-0.1.0}
-
-  __file=${__dir}/semversort
-  echo "Fetching https://github.com/rikby/semversort/releases/download/${version}/semversort..."
-
-  curl -Ls https://github.com/rikby/semversort/releases/download/${version}/semversort --output ${__file} --fail || \
-    err=$? && echo "error: [${err}] No such version or bad connection." && exit ${err}
-
-  chmod u+x ${__file} && \
-    echo 'Semantic version sort: '${__file} && \
-    exit 0
-
-  exit 1
+__dir=/usr/local/bin
+if [ ! -d ${__dir} ]; then
+  __dir=/usr/bin
 fi
+
+version=${1:-0.1.0}
+
+__file=${__dir}/semversort
+echo "Fetching https://github.com/rikby/semversort/releases/download/${version}/semversort..."
+
+curl -Ls https://github.com/rikby/semversort/releases/download/${version}/semversort --output ${__file} --fail || \
+  err=$? && echo "error: [${err}] No such version or bad connection." && exit ${err}
+
+chmod u+x ${__file} && \
+  echo 'Semantic version sort: '${__file} && \
+  exit 0
+
+exit 1
